### ISSUE TITLE
UnicodeDecodeError for UTF-8 files

### ISSUE THREAD

**Issue by ek68794998** [frehder/mbox2eml#3]
The script runs into a `UnicodeDecodeError` when working with emails that have UTF-8 characters (such as emoji or foreign language characters).

```
Traceback (most recent call last):
  File "C:\fakepath\mbox2eml\mbox2eml.py", line 46, in <module>
    for line in mbox_file:
  File "C:\fakepath\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1004: character maps to <undefined>
```

This can be fixed by adding `encoding="utf-8"` in each of the four `open()` calls:

![image](https://user-images.githubusercontent.com/1350074/202829182-a284e8b9-2088-47b6-82a8-1507823339ad.png)

**Comment by frehder** [comment]
Thank you for pointing this out. Unfortunately due to time constraints I am not able to maintain this projekt anymore. Sorry about that.

**Comment by ek68794998** [comment]
No worries; thanks for the response.

Perhaps this issue will be useful to someone else in the future who runs into the same issue.
